# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b'\x1d\xfb(\xc3'
full_git_hash = '1dfb28c334d592d155444c108920c70c18b9d214'
git_branch = 'HEAD'
dirty = False
