# coding: utf-8

"""
    Imperva Advanced API Security

    This topic describes the API for Imperva Advanced API Security. For full feature documentation, see [Imperva API Security](https://docs.imperva.com/bundle/api-security/page/72248.htm).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DuplicateEndpointResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'full_path': 'str',
        'method': 'str'
    }

    attribute_map = {
        'id': 'id',
        'full_path': 'fullPath',
        'method': 'method'
    }

    def __init__(self, id=None, full_path=None, method=None):  # noqa: E501
        """DuplicateEndpointResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._full_path = None
        self._method = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if full_path is not None:
            self.full_path = full_path
        if method is not None:
            self.method = method

    @property
    def id(self):
        """Gets the id of this DuplicateEndpointResponse.  # noqa: E501

        The endpoint ID  # noqa: E501

        :return: The id of this DuplicateEndpointResponse.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DuplicateEndpointResponse.

        The endpoint ID  # noqa: E501

        :param id: The id of this DuplicateEndpointResponse.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def full_path(self):
        """Gets the full_path of this DuplicateEndpointResponse.  # noqa: E501

        The endpoint full path  # noqa: E501

        :return: The full_path of this DuplicateEndpointResponse.  # noqa: E501
        :rtype: str
        """
        return self._full_path

    @full_path.setter
    def full_path(self, full_path):
        """Sets the full_path of this DuplicateEndpointResponse.

        The endpoint full path  # noqa: E501

        :param full_path: The full_path of this DuplicateEndpointResponse.  # noqa: E501
        :type: str
        """

        self._full_path = full_path

    @property
    def method(self):
        """Gets the method of this DuplicateEndpointResponse.  # noqa: E501

        The endpoint HTTP method  # noqa: E501

        :return: The method of this DuplicateEndpointResponse.  # noqa: E501
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this DuplicateEndpointResponse.

        The endpoint HTTP method  # noqa: E501

        :param method: The method of this DuplicateEndpointResponse.  # noqa: E501
        :type: str
        """
        allowed_values = ["POST", "GET", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]  # noqa: E501
        if method not in allowed_values:
            raise ValueError(
                "Invalid value for `method` ({0}), must be one of {1}"  # noqa: E501
                .format(method, allowed_values)
            )

        self._method = method

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DuplicateEndpointResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DuplicateEndpointResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
