# coding: utf-8

"""
    Imperva Advanced API Security

    This topic describes the API for Imperva Advanced API Security. For full feature documentation, see [Imperva API Security](https://docs.imperva.com/bundle/api-security/page/72248.htm).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RequestDrillDown(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'query_param_list': 'list[ParameterDrillDown]',
        'content_type_to_request_body': 'dict(str, list[ParameterDrillDown])'
    }

    attribute_map = {
        'query_param_list': 'queryParamList',
        'content_type_to_request_body': 'contentTypeToRequestBody'
    }

    def __init__(self, query_param_list=None, content_type_to_request_body=None):  # noqa: E501
        """RequestDrillDown - a model defined in Swagger"""  # noqa: E501
        self._query_param_list = None
        self._content_type_to_request_body = None
        self.discriminator = None
        if query_param_list is not None:
            self.query_param_list = query_param_list
        if content_type_to_request_body is not None:
            self.content_type_to_request_body = content_type_to_request_body

    @property
    def query_param_list(self):
        """Gets the query_param_list of this RequestDrillDown.  # noqa: E501


        :return: The query_param_list of this RequestDrillDown.  # noqa: E501
        :rtype: list[ParameterDrillDown]
        """
        return self._query_param_list

    @query_param_list.setter
    def query_param_list(self, query_param_list):
        """Sets the query_param_list of this RequestDrillDown.


        :param query_param_list: The query_param_list of this RequestDrillDown.  # noqa: E501
        :type: list[ParameterDrillDown]
        """

        self._query_param_list = query_param_list

    @property
    def content_type_to_request_body(self):
        """Gets the content_type_to_request_body of this RequestDrillDown.  # noqa: E501


        :return: The content_type_to_request_body of this RequestDrillDown.  # noqa: E501
        :rtype: dict(str, list[ParameterDrillDown])
        """
        return self._content_type_to_request_body

    @content_type_to_request_body.setter
    def content_type_to_request_body(self, content_type_to_request_body):
        """Sets the content_type_to_request_body of this RequestDrillDown.


        :param content_type_to_request_body: The content_type_to_request_body of this RequestDrillDown.  # noqa: E501
        :type: dict(str, list[ParameterDrillDown])
        """

        self._content_type_to_request_body = content_type_to_request_body

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestDrillDown, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestDrillDown):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
