
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-28T08:24:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1865e785c5a91f1e59f2c2bc502141ee581283f5",
 "version": "0.7.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
