import ast

class ClassInfo:
    def __init__(self, name: str, excluded_attributes: list[str] = []) -> None: ...

class ClassFinder(ast.NodeVisitor):
    def __init__(self, excluded_attributes: list[str] = []) -> None: ...
    def visit_ClassDef(self, node) -> None: ...
