def get_var_name(variable, local_vars): ...
def is_valid_class_name(name: str) -> bool: ...
def to_valid_class_name(name: str, previous_replacements: list[str] = []) -> str: ...
def table_to_python_class(table_name) -> str: ...
