from ibis import Schema as Schema

class VinylSchema:
    def __init__(self, schema: Schema) -> None: ...
    def items(self): ...
    @property
    def names(self) -> list[str]: ...
    @property
    def types(self) -> list[str]: ...
    def __rich__(self): ...
