from _typeshed import Incomplete
from vinyl.lib.project import Project as Project
from vinyl.lib.table import VinylTable as VinylTable

class QueryEngineResult:
    table: Incomplete
    def __init__(self, table: VinylTable) -> None: ...
    def to_pandas(self): ...
    def to_records(self): ...
    def columns(self): ...
    def numpy_rows(self): ...

class QueryEngine:
    project: Incomplete
    def __init__(self, project: Project) -> None: ...
