# coding: utf-8

"""
    Imperva SIEM Configurations API 3.0

    Set up and manage the Imperva SIEM log integration.  - Create, view, and edit connections to your log storage repository.  - Configure which logs you want to receive from Imperva, and where to receive them.  For full feature documentation, see  [Near Real-Time SIEM Log Integration](https://docs.imperva.com/bundle/cloud-application-security/page/siem-log-configuration.htm).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.connection_dto_response import ConnectionDtoResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestConnectionDtoResponse(unittest.TestCase):
    """ConnectionDtoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectionDtoResponse(self):
        """Test ConnectionDtoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.connection_dto_response.ConnectionDtoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
