# coding: utf-8

"""
    Imperva SIEM Configurations API 3.0

    Set up and manage the Imperva SIEM log integration.  - Create, view, and edit connections to your log storage repository.  - Configure which logs you want to receive from Imperva, and where to receive them.  For full feature documentation, see  [Near Real-Time SIEM Log Integration](https://docs.imperva.com/bundle/cloud-application-security/page/siem-log-configuration.htm).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.connections_api import ConnectionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConnectionsApi(unittest.TestCase):
    """ConnectionsApi unit test stubs"""

    def setUp(self):
        self.api = ConnectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create1(self):
        """Test case for create1

        Create connection  # noqa: E501
        """
        pass

    def test_delete1(self):
        """Test case for delete1

        Delete connection  # noqa: E501
        """
        pass

    def test_get1(self):
        """Test case for get1

        Retrieve connection  # noqa: E501
        """
        pass

    def test_get_all1(self):
        """Test case for get_all1

        Retrieve all connections  # noqa: E501
        """
        pass

    def test_update1(self):
        """Test case for update1

        Overwrite connection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
