# coding: utf-8

"""
    Cloud Application Security API

    Imperva provides customers and partners with the ability to manage accounts and sites via an API. For more information, see <a style=\"text-decoration:none\" href=\"https://docs.imperva.com/csh?context=my_api\">Cloud Application Security API Reference</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.time_series_item import TimeSeriesItem  # noqa: E501
from swagger_client.rest import ApiException


class TestTimeSeriesItem(unittest.TestCase):
    """TimeSeriesItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeSeriesItem(self):
        """Test TimeSeriesItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.time_series_item.TimeSeriesItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
