# coding: utf-8

"""
    Cloud Application Security API

    Imperva provides customers and partners with the ability to manage accounts and sites via an API. For more information, see <a style=\"text-decoration:none\" href=\"https://docs.imperva.com/csh?context=my_api\">Cloud Application Security API Reference</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.site_management_api import SiteManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSiteManagementApi(unittest.TestCase):
    """SiteManagementApi unit test stubs"""

    def setUp(self):
        self.api = SiteManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_cache_rule(self):
        """Test case for add_cache_rule

        Add a cache rule  # noqa: E501
        """
        pass

    def test_add_custom_rule(self):
        """Test case for add_custom_rule

        Add rule  # noqa: E501
        """
        pass

    def test_add_data_center(self):
        """Test case for add_data_center

        Add data center  # noqa: E501
        """
        pass

    def test_add_dc_server(self):
        """Test case for add_dc_server

        Add server  # noqa: E501
        """
        pass

    def test_add_site(self):
        """Test case for add_site

        Add a site  # noqa: E501
        """
        pass

    def test_check_caa_compliance(self):
        """Test case for check_caa_compliance

        Check CAA compliance  # noqa: E501
        """
        pass

    def test_create_new_csr(self):
        """Test case for create_new_csr

        Create new CSR  # noqa: E501
        """
        pass

    def test_delete_cache_rule(self):
        """Test case for delete_cache_rule

        Delete a cache rule  # noqa: E501
        """
        pass

    def test_delete_custom_rule(self):
        """Test case for delete_custom_rule

        Delete rule  # noqa: E501
        """
        pass

    def test_delete_data_center(self):
        """Test case for delete_data_center

        Delete data center  # noqa: E501
        """
        pass

    def test_delete_dc_server(self):
        """Test case for delete_dc_server

        Delete server  # noqa: E501
        """
        pass

    def test_delete_site(self):
        """Test case for delete_site

        Delete site  # noqa: E501
        """
        pass

    def test_domain_emails(self):
        """Test case for domain_emails

        Get domain approver e-mail addresses  # noqa: E501
        """
        pass

    def test_edit_bots_configuration(self):
        """Test case for edit_bots_configuration

        Update website bot configuration  # noqa: E501
        """
        pass

    def test_edit_cache_rule(self):
        """Test case for edit_cache_rule

        Edit a cache rule  # noqa: E501
        """
        pass

    def test_edit_custom_rule(self):
        """Test case for edit_custom_rule

        Edit rule  # noqa: E501
        """
        pass

    def test_edit_data_center(self):
        """Test case for edit_data_center

        Edit data center  # noqa: E501
        """
        pass

    def test_edit_dc_server(self):
        """Test case for edit_dc_server

        Edit server  # noqa: E501
        """
        pass

    def test_enable_cache_shield(self):
        """Test case for enable_cache_shield

        Enable cache shield  # noqa: E501
        """
        pass

    def test_enable_disable_cache_rule(self):
        """Test case for enable_disable_cache_rule

        Enable or disable cache rule  # noqa: E501
        """
        pass

    def test_enable_disable_custom_rule(self):
        """Test case for enable_disable_custom_rule

        Enable or disable rule  # noqa: E501
        """
        pass

    def test_get_advanced_caching_settings(self):
        """Test case for get_advanced_caching_settings

        Get advanced caching settings  # noqa: E501
        """
        pass

    def test_get_bots_configuration(self):
        """Test case for get_bots_configuration

        Get website bot configuration  # noqa: E501
        """
        pass

    def test_get_cache404_settings(self):
        """Test case for get_cache404_settings

        Get cache 404 settings  # noqa: E501
        """
        pass

    def test_get_caching_mode(self):
        """Test case for get_caching_mode

        Get caching mode  # noqa: E501
        """
        pass

    def test_get_data_region(self):
        """Test case for get_data_region

        Get site data storage region  # noqa: E501
        """
        pass

    def test_get_html_injection_rules(self):
        """Test case for get_html_injection_rules

        Get HTML injection rules  # noqa: E501
        """
        pass

    def test_get_override_site_regions_by_geo(self):
        """Test case for get_override_site_regions_by_geo

        Check site regions by origin geolocation  # noqa: E501
        """
        pass

    def test_get_recommended_data_center_origin_po_ps(self):
        """Test case for get_recommended_data_center_origin_po_ps

        Get data center recommended origin PoPs  # noqa: E501
        """
        pass

    def test_get_response_header_settings(self):
        """Test case for get_response_header_settings

        Get cached response headers  # noqa: E501
        """
        pass

    def test_get_rewrite_ports(self):
        """Test case for get_rewrite_ports

        Get rewrite port  # noqa: E501
        """
        pass

    def test_get_secure_resources_mode(self):
        """Test case for get_secure_resources_mode

        Get secure resources mode  # noqa: E501
        """
        pass

    def test_get_site_error_page_template(self):
        """Test case for get_site_error_page_template

        Get error page  # noqa: E501
        """
        pass

    def test_get_site_report(self):
        """Test case for get_site_report

        Get site report  # noqa: E501
        """
        pass

    def test_get_stale_content(self):
        """Test case for get_stale_content

        Get stale content settings  # noqa: E501
        """
        pass

    def test_get_tag_response_header(self):
        """Test case for get_tag_response_header

        Get header to tag responses by  # noqa: E501
        """
        pass

    def test_get_tls_configuration(self):
        """Test case for get_tls_configuration

        Get website TLS configuration  # noqa: E501
        """
        pass

    def test_get_xray_link(self):
        """Test case for get_xray_link

        Get XRay access link  # noqa: E501
        """
        pass

    def test_is_cache_shield_enabled(self):
        """Test case for is_cache_shield_enabled

        Is cache shield enabled  # noqa: E501
        """
        pass

    def test_list_account_custom_rules(self):
        """Test case for list_account_custom_rules

        List account rules  # noqa: E501
        """
        pass

    def test_list_cache_rules(self):
        """Test case for list_cache_rules

        List cache rules for a given site  # noqa: E501
        """
        pass

    def test_list_custom_rules(self):
        """Test case for list_custom_rules

        List rules  # noqa: E501
        """
        pass

    def test_list_data_centers(self):
        """Test case for list_data_centers

        List data centers  # noqa: E501
        """
        pass

    def test_list_data_centers_configuration(self):
        """Test case for list_data_centers_configuration

        get site's data centers' configuration  # noqa: E501
        """
        pass

    def test_list_sites(self):
        """Test case for list_sites

        List sites  # noqa: E501
        """
        pass

    def test_modify_advanced_caching_settings(self):
        """Test case for modify_advanced_caching_settings

        Advanced caching settings  # noqa: E501
        """
        pass

    def test_modify_cache404_settings(self):
        """Test case for modify_cache404_settings

        Modify cache 404 settings  # noqa: E501
        """
        pass

    def test_modify_purge_settings(self):
        """Test case for modify_purge_settings

        Purge resources  # noqa: E501
        """
        pass

    def test_modify_response_header_settings(self):
        """Test case for modify_response_header_settings

        Modify cached response headers  # noqa: E501
        """
        pass

    def test_modify_rewrite_ports(self):
        """Test case for modify_rewrite_ports

        Modify rewrite port  # noqa: E501
        """
        pass

    def test_modify_site_configuration(self):
        """Test case for modify_site_configuration

        Modify site configuration  # noqa: E501
        """
        pass

    def test_modify_site_error_page_template(self):
        """Test case for modify_site_error_page_template

        Modify error page  # noqa: E501
        """
        pass

    def test_modify_site_log_level(self):
        """Test case for modify_site_log_level

        Modify site logs level  # noqa: E501
        """
        pass

    def test_modify_site_security_configuration(self):
        """Test case for modify_site_security_configuration

        Modify site security configuration  # noqa: E501
        """
        pass

    def test_modify_site_support_deprecated_tls(self):
        """Test case for modify_site_support_deprecated_tls

        Set support for all TLS versions  # noqa: E501
        """
        pass

    def test_modify_stale_content(self):
        """Test case for modify_stale_content

        Modify stale content settings  # noqa: E501
        """
        pass

    def test_modify_tag_response_header(self):
        """Test case for modify_tag_response_header

        Tag the response according to the value of a header  # noqa: E501
        """
        pass

    def test_move_site(self):
        """Test case for move_site

        Move site  # noqa: E501
        """
        pass

    def test_purge_hostname(self):
        """Test case for purge_hostname

        Purge hostname from cache  # noqa: E501
        """
        pass

    def test_purge_site_cache(self):
        """Test case for purge_site_cache

        Purge site cache  # noqa: E501
        """
        pass

    def test_put_data_centers_configuration(self):
        """Test case for put_data_centers_configuration

        set site's data centers' configuration  # noqa: E501
        """
        pass

    def test_remove_custom_certificate(self):
        """Test case for remove_custom_certificate

        Remove custom certificate  # noqa: E501
        """
        pass

    def test_resume_traffic_to_active_dcs(self):
        """Test case for resume_traffic_to_active_dcs

        Resume traffic to your active data centers  # noqa: E501
        """
        pass

    def test_set_caching_mode(self):
        """Test case for set_caching_mode

        Modify caching mode  # noqa: E501
        """
        pass

    def test_set_data_center_origin_po_p(self):
        """Test case for set_data_center_origin_po_p

        Set data center origin PoP  # noqa: E501
        """
        pass

    def test_set_data_region(self):
        """Test case for set_data_region

        Set site data storage region  # noqa: E501
        """
        pass

    def test_set_html_injection_rule(self):
        """Test case for set_html_injection_rule

        Add, replace or remove a HTML injection rule  # noqa: E501
        """
        pass

    def test_set_override_site_regions_by_geo(self):
        """Test case for set_override_site_regions_by_geo

        Set site regions by origin geolocation  # noqa: E501
        """
        pass

    def test_set_priority(self):
        """Test case for set_priority

        Set rule priority  # noqa: E501
        """
        pass

    def test_set_secure_resources_mode(self):
        """Test case for set_secure_resources_mode

        Modify secure resources mode  # noqa: E501
        """
        pass

    def test_site_status(self):
        """Test case for site_status

        Get site status  # noqa: E501
        """
        pass

    def test_update_tls_configuration(self):
        """Test case for update_tls_configuration

        Update website TLS configuration  # noqa: E501
        """
        pass

    def test_upload_custom_certificate(self):
        """Test case for upload_custom_certificate

        Upload custom certificate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
