# coding: utf-8

"""
    Cloud Application Security API

    Imperva provides customers and partners with the ability to manage accounts and sites via an API. For more information, see <a style=\"text-decoration:none\" href=\"https://docs.imperva.com/csh?context=my_api\">Cloud Application Security API Reference</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.waf_log_setup_api import WAFLogSetupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWAFLogSetupApi(unittest.TestCase):
    """WAFLogSetupApi unit test stubs"""

    def setUp(self):
        self.api = WAFLogSetupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate(self):
        """Test case for activate

        Activate WAF Logs  # noqa: E501
        """
        pass

    def test_change_status(self):
        """Test case for change_status

        Change logs collector configuration status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
