# coding: utf-8

"""
    Imperva Advanced API Security

    This topic describes the API for Imperva Advanced API Security. For full feature documentation, see [Imperva API Security](https://docs.imperva.com/bundle/api-security/page/72248.htm).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.endpoints_per_host import EndpointsPerHost  # noqa: E501
from swagger_client.rest import ApiException


class TestEndpointsPerHost(unittest.TestCase):
    """EndpointsPerHost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpointsPerHost(self):
        """Test EndpointsPerHost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.endpoints_per_host.EndpointsPerHost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
