
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-29T16:48:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "762d72cf66260b2fde06aa68d935960c6b1fe45b",
 "version": "3.3.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
