# coding: utf-8

"""
    Attack Analytics API

    Access the Attack Analytics data for your account using the API. For full feature documentation, see [Imperva Attack Analytics](https://docs.imperva.com/bundle/Attack-Analytics/page/Content/attack_analytics/attack_analytics.htm).  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.attack_analytics_api import AttackAnalyticsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAttackAnalyticsApi(unittest.TestCase):
    """AttackAnalyticsApi unit test stubs"""

    def setUp(self):
        self.api = AttackAnalyticsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_incident_stats_by_account(self):
        """Test case for get_incident_stats_by_account

        Retrieve incident details  # noqa: E501
        """
        pass

    def test_get_incidents_by_account(self):
        """Test case for get_incidents_by_account

        Retrieve a list of incidents  # noqa: E501
        """
        pass

    def test_get_insights_per_account(self):
        """Test case for get_insights_per_account

        Retrieve insights  # noqa: E501
        """
        pass

    def test_get_sample_events_by_incident(self):
        """Test case for get_sample_events_by_incident

        Retrieve event sample  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
