# coding: utf-8

"""
    Attack Analytics API

    Access the Attack Analytics data for your account using the API. For full feature documentation, see [Imperva Attack Analytics](https://docs.imperva.com/bundle/Attack-Analytics/page/Content/attack_analytics/attack_analytics.htm).  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.network_traffic_data import NetworkTrafficData  # noqa: E501
from swagger_client.rest import ApiException


class TestNetworkTrafficData(unittest.TestCase):
    """NetworkTrafficData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkTrafficData(self):
        """Test NetworkTrafficData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.network_traffic_data.NetworkTrafficData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
