
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-01T09:12:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0c2893d6f00932504e8da16bce776d5cb17492a",
 "version": "2.33.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
