
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-29T11:01:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "11cb641c65df262cb519b9ad2060c5c45241b78d",
 "version": "2.16.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
