
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-03T10:44:52-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "e40e2a88e5b9d04f0f72df4d23e0f15b1d00d62f",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
