# coding: utf-8

"""
    @ledge/api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ledge_python_sdk.api.leaderboard_api import LeaderboardApi


class TestLeaderboardApi(unittest.TestCase):
    """LeaderboardApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LeaderboardApi()

    def tearDown(self) -> None:
        pass

    def test_get_current_leaderboard(self) -> None:
        """Test case for get_current_leaderboard

        """
        pass

    def test_get_ranks(self) -> None:
        """Test case for get_ranks

        """
        pass

    def test_get_user_rank(self) -> None:
        """Test case for get_user_rank

        """
        pass


if __name__ == '__main__':
    unittest.main()
