# coding: utf-8

"""
    @ledge/api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ledge_python_sdk.models.create_quest_request import CreateQuestRequest

class TestCreateQuestRequest(unittest.TestCase):
    """CreateQuestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateQuestRequest:
        """Test CreateQuestRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateQuestRequest`
        """
        model = CreateQuestRequest()
        if include_optional:
            return CreateQuestRequest(
                description = '',
                title = ''
            )
        else:
            return CreateQuestRequest(
                description = '',
                title = '',
        )
        """

    def testCreateQuestRequest(self):
        """Test CreateQuestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
