# coding: utf-8

"""
    Cloud Application Security API

    Imperva provides customers and partners with the ability to manage accounts and sites via an API. For more information, see <a style=\"text-decoration:none\" href=\"https://docs.imperva.com/csh?context=my_api\">Cloud Application Security API Reference</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ADRuleSeries(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'action': 'str',
        'created_at': 'datetime',
        'updated_by': 'str',
        'hits': 'list[object]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'action': 'action',
        'created_at': 'createdAt',
        'updated_by': 'updatedBy',
        'hits': 'hits'
    }

    def __init__(self, id=None, name=None, action=None, created_at=None, updated_by=None, hits=None):  # noqa: E501
        """ADRuleSeries - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._action = None
        self._created_at = None
        self._updated_by = None
        self._hits = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if action is not None:
            self.action = action
        if created_at is not None:
            self.created_at = created_at
        if updated_by is not None:
            self.updated_by = updated_by
        if hits is not None:
            self.hits = hits

    @property
    def id(self):
        """Gets the id of this ADRuleSeries.  # noqa: E501


        :return: The id of this ADRuleSeries.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ADRuleSeries.


        :param id: The id of this ADRuleSeries.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ADRuleSeries.  # noqa: E501


        :return: The name of this ADRuleSeries.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ADRuleSeries.


        :param name: The name of this ADRuleSeries.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def action(self):
        """Gets the action of this ADRuleSeries.  # noqa: E501


        :return: The action of this ADRuleSeries.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this ADRuleSeries.


        :param action: The action of this ADRuleSeries.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def created_at(self):
        """Gets the created_at of this ADRuleSeries.  # noqa: E501


        :return: The created_at of this ADRuleSeries.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ADRuleSeries.


        :param created_at: The created_at of this ADRuleSeries.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_by(self):
        """Gets the updated_by of this ADRuleSeries.  # noqa: E501


        :return: The updated_by of this ADRuleSeries.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this ADRuleSeries.


        :param updated_by: The updated_by of this ADRuleSeries.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    @property
    def hits(self):
        """Gets the hits of this ADRuleSeries.  # noqa: E501


        :return: The hits of this ADRuleSeries.  # noqa: E501
        :rtype: list[object]
        """
        return self._hits

    @hits.setter
    def hits(self, hits):
        """Sets the hits of this ADRuleSeries.


        :param hits: The hits of this ADRuleSeries.  # noqa: E501
        :type: list[object]
        """

        self._hits = hits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ADRuleSeries, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ADRuleSeries):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
