# coding: utf-8

"""
    Deci Platform API

    Train, deploy, optimize and serve your models using Deci's platform, in your cloud or on premise.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import deci_platform_client
from deci_platform_client.model.body_validate_model_name import BodyValidateModelName
from deci_platform_client import configuration


class TestBodyValidateModelName(unittest.TestCase):
    """BodyValidateModelName unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
