# coding: utf-8

"""
    User Management API

    This is an API for Imperva User Management  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RequestedAssignment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_email': 'str',
        'account_id': 'int',
        'role_ids': 'list[int]'
    }

    attribute_map = {
        'user_email': 'userEmail',
        'account_id': 'accountId',
        'role_ids': 'roleIds'
    }

    def __init__(self, user_email=None, account_id=None, role_ids=None):  # noqa: E501
        """RequestedAssignment - a model defined in Swagger"""  # noqa: E501
        self._user_email = None
        self._account_id = None
        self._role_ids = None
        self.discriminator = None
        if user_email is not None:
            self.user_email = user_email
        if account_id is not None:
            self.account_id = account_id
        if role_ids is not None:
            self.role_ids = role_ids

    @property
    def user_email(self):
        """Gets the user_email of this RequestedAssignment.  # noqa: E501

        The email of the user that was acted on.  # noqa: E501

        :return: The user_email of this RequestedAssignment.  # noqa: E501
        :rtype: str
        """
        return self._user_email

    @user_email.setter
    def user_email(self, user_email):
        """Sets the user_email of this RequestedAssignment.

        The email of the user that was acted on.  # noqa: E501

        :param user_email: The user_email of this RequestedAssignment.  # noqa: E501
        :type: str
        """

        self._user_email = user_email

    @property
    def account_id(self):
        """Gets the account_id of this RequestedAssignment.  # noqa: E501

        ID of the account that was acted on.  # noqa: E501

        :return: The account_id of this RequestedAssignment.  # noqa: E501
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this RequestedAssignment.

        ID of the account that was acted on.  # noqa: E501

        :param account_id: The account_id of this RequestedAssignment.  # noqa: E501
        :type: int
        """

        self._account_id = account_id

    @property
    def role_ids(self):
        """Gets the role_ids of this RequestedAssignment.  # noqa: E501

        List of roles IDs to add to the user.  # noqa: E501

        :return: The role_ids of this RequestedAssignment.  # noqa: E501
        :rtype: list[int]
        """
        return self._role_ids

    @role_ids.setter
    def role_ids(self, role_ids):
        """Sets the role_ids of this RequestedAssignment.

        List of roles IDs to add to the user.  # noqa: E501

        :param role_ids: The role_ids of this RequestedAssignment.  # noqa: E501
        :type: list[int]
        """

        self._role_ids = role_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestedAssignment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestedAssignment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
