# coding: utf-8

"""
    Imperva Website Domain Management

    Manage the domains that are sharing the CNAME of an onboarded website.<br/>All domains that are using the same CNAME share the website configuration settings and policies of the onboarded website.<br/>For full feature documentation, see <a href=\"https://docs.imperva.com/bundle/cloud-application-security/page/website-general-settings.htm\">Website General Settings</a>.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.site_domain_details import SiteDomainDetails  # noqa: E501
from swagger_client.rest import ApiException


class TestSiteDomainDetails(unittest.TestCase):
    """SiteDomainDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiteDomainDetails(self):
        """Test SiteDomainDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.site_domain_details.SiteDomainDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
