# coding: utf-8

"""
    Imperva Policy Management

    Create policies to centrally configure settings and apply them to multiple websites in your account. For full feature documentation, see <a style=\"text-decoration:none\" href=\"https://docs.imperva.com/csh?context=policies\">Create and Manage Policies</a>.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.policy_management_api import PolicyManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPolicyManagementApi(unittest.TestCase):
    """PolicyManagementApi unit test stubs"""

    def setUp(self):
        self.api = PolicyManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_if_policy_is_applied_on_asset(self):
        """Test case for check_if_policy_is_applied_on_asset

        Check whether the policy is applied on the asset  # noqa: E501
        """
        pass

    def test_create_new_policy(self):
        """Test case for create_new_policy

        Add a new policy or copy an existing policy  # noqa: E501
        """
        pass

    def test_delete_policy(self):
        """Test case for delete_policy

        Delete an existing policy  # noqa: E501
        """
        pass

    def test_get_all_policies_by_account(self):
        """Test case for get_all_policies_by_account

        Retrieve all policies in account  # noqa: E501
        """
        pass

    def test_get_policy_by_id(self):
        """Test case for get_policy_by_id

        Retrieve policy details  # noqa: E501
        """
        pass

    def test_modify_policy(self):
        """Test case for modify_policy

        Modify an existing policy (partial update)  # noqa: E501
        """
        pass

    def test_update_policy(self):
        """Test case for update_policy

        Overwrite an existing policy (full update)  # noqa: E501
        """
        pass

    def test_update_policy_to_single_asset(self):
        """Test case for update_policy_to_single_asset

        Overwrite applied assets in a policy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
