# coding: utf-8

"""
    Imperva Subscription Management API

    Access the subscription data for your account using the API. For the full feature documentation, see [Subscription status](https://docs.imperva.com/bundle/cloud-application-security/page/settings/subscription.htm).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.subscription_resource_dto import SubscriptionResourceDto  # noqa: E501
from swagger_client.rest import ApiException


class TestSubscriptionResourceDto(unittest.TestCase):
    """SubscriptionResourceDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriptionResourceDto(self):
        """Test SubscriptionResourceDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.subscription_resource_dto.SubscriptionResourceDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
