# coding: utf-8

"""
    SSL Certificate Management

    View and manage certificates for all websites in your account.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.hsm_certificates_api import HSMCertificatesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHSMCertificatesApi(unittest.TestCase):
    """HSMCertificatesApi unit test stubs"""

    def setUp(self):
        self.api = HSMCertificatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_latency(self):
        """Test case for get_latency

        Get HSM latency  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
