# coding: utf-8

"""
    SSL Certificate Management

    View and manage certificates for all websites in your account.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ssl_certificates_api import SSLCertificatesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSSLCertificatesApi(unittest.TestCase):
    """SSLCertificatesApi unit test stubs"""

    def setUp(self):
        self.api = SSLCertificatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_san_validation_method(self):
        """Test case for change_san_validation_method

        Change SAN validation method  # noqa: E501
        """
        pass

    def test_get_certificates1(self):
        """Test case for get_certificates1

        Get certificate details  # noqa: E501
        """
        pass

    def test_san_instructions_for_account(self):
        """Test case for san_instructions_for_account

        Get domain validation instructions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
