# coding: utf-8

"""
    SSL Certificate Management

    View and manage certificates for all websites in your account.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.san_instructions_dto import SanInstructionsDto  # noqa: E501
from swagger_client.rest import ApiException


class TestSanInstructionsDto(unittest.TestCase):
    """SanInstructionsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSanInstructionsDto(self):
        """Test SanInstructionsDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.san_instructions_dto.SanInstructionsDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
