# coding: utf-8

"""
    Account Takeover Protection API

    This is the API documentation for Imperva Account Takeover Protection. ATO detects and mitigates account takeover attempts, protecting your web applications against volumetric and low and slow ATO attacks. For the full feature documentation, see https://docs.imperva.com/bundle/account-takeover.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.top_sources_api import TopSourcesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTopSourcesApi(unittest.TestCase):
    """TopSourcesApi unit test stubs"""

    def setUp(self):
        self.api = TopSourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_top_sources_stats(self):
        """Test case for get_all_top_sources_stats

        Get all the top stats (country, client, reputation, successful user, ip, ip+fingerprint).  # noqa: E501
        """
        pass

    def test_get_top_clients(self):
        """Test case for get_top_clients

        Get top number of requests by client of unique users for the current time period compared to previous time period  # noqa: E501
        """
        pass

    def test_get_top_countries(self):
        """Test case for get_top_countries

        Get top number of requests by country of unique users for the current time period compared to previous time period  # noqa: E501
        """
        pass

    def test_get_top_ips(self):
        """Test case for get_top_ips

        Get top number of requests by IP of unique users for the current time period compared to previous time period  # noqa: E501
        """
        pass

    def test_get_top_ips_fps(self):
        """Test case for get_top_ips_fps

        Get top number of requests by IP + Fingerprint of unique users for the current time period compared to previous time period  # noqa: E501
        """
        pass

    def test_get_top_reputation(self):
        """Test case for get_top_reputation

        Get top number of requests by reputation of unique users for the current time period compared to previous time period  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
