from typing import Any, Callable
from vinyl.lib.enums import AssetType as AssetType
from vinyl.lib.metric import MetricStore as MetricStore
from vinyl.lib.table import VinylTable as VinylTable

def model(deps: object | Callable[..., Any] | list[object | Callable[..., Any]], publish: bool = False, tags: str | list[str] | None = None): ...
def metric(deps: object | Callable[..., Any] | list[object | Callable[..., Any]], publish: bool = False, tags: str | list[str] | None = None): ...
def resource(func: Callable[..., Any]): ...
