
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-31T02:11:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7922ba77212b5dd51c102c3b5736fc53e69408a0",
 "version": "1.4.dev2413"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
