# Generated by Django 4.2.10 on 2024-03-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('ship_id', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('reimbursement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='srppayouts.reimbursement')),
                ('ship', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='srppayouts.ship')),
            ],
        ),
    ]
