# Generated by Django 4.2.10 on 2024-03-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0002_reimbursement_ship_payout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('admin_access', 'Can force to recalculate the table'))},
        ),
    ]
