# coding: utf-8

"""
    User Management API

    This is an API for Imperva User Management  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_management_api_exception import UserManagementApiException  # noqa: E501
from swagger_client.rest import ApiException


class TestUserManagementApiException(unittest.TestCase):
    """UserManagementApiException unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserManagementApiException(self):
        """Test UserManagementApiException"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_management_api_exception.UserManagementApiException()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
